# This is a basic workflow to help you get started with Actions

name: linkedevents-ci

on:
  push:
    branches: [ master, develop-workflow ] # TODO revert
  pull_request:
    branches: [ master, develop-workflow ] # TODO revert

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  POSTGRES_DB: test_linkedevents
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  DATABASE_URL: "postgis://postgres:postgres@localhost/test_linkedevents"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]
    services:
      postgres:
        image: helsinkitest/postgis:9.6-2.5-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_linkedevents
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev

      - name: System requirements for Django
        run:  sudo apt-get install gdal-bin gettext postgresql-client

      - name: Setup postgres extensions
        run: ./.github/scripts/postgres-setup.sh
        shell: bash
        env:
          psql: "psql -v ON_ERROR_STOP=1 --username postgres --no-password"
          PGUSER: "postgres"
          PGPASSWORD: "postgres"
          PGHOST: "localhost"
          PGPORT: 5432


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codecov -r requirements.txt -r requirements-dev.txt

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      # Disabled until LINK-1126 is done
      #- name: Check migrations
      #  run: |
      #    python manage.py makemigrations --dry-run --check

      - name: Apply migrations
        run: |
          python manage.py migrate

      - name: Check black
        run: |
          black --check .

      - name: Check flake8
        continue-on-error: true # TODO remove
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: flake8
          run: flake8

      - name: Check isort
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: isort
          run: isort . --check-only --diff

      # With pytest-cov use: --cov=.
      # Some errors, skipping --doctest-modules for now
      - name: Run tests
        continue-on-error: true # TODO remove
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: pytest
          run: pytest -ra -vvv --cov=.

      #- name: Run codecov
      #  run: codecov
      - uses: codecov/codecov-action@v3